// 신규 컴파일 전용 빌드 설정, 빌드속도 약 3배 이상 향상 된다고 알려져 있음
/////////////////////////////////////
// Engine
/////////////////////////////////////
#include "Vector2.cpp"
#include "Scene.cpp"
#include "Gamemanager.cpp"
#include "Timemanager.cpp"
#include "ObjectManager.cpp"
#include "Scenemanager.cpp"
#include "SoundManager.cpp"
#include "Object.cpp"
#include "GameObject.cpp"
#include "Transform.cpp"
#include "Renderer.cpp"
#include "Component.cpp"
#include "Animation.cpp"
#include "AnimationClip.cpp"
#include "input.cpp"
#include "Bitmap.cpp"
#include "image.cpp"
#include "LOG_MGR.cpp"
#include "Physic.cpp"
/////////////////////////////////////
// GameProject
/////////////////////////////////////
#include "Titlescene.cpp"
#include "MainGameScene.cpp"
#include "Attack.cpp"
#include "SimpleAttack.cpp"
#include "BackGround.cpp"
#include "MapBackGround.cpp"
#include "MapColider.cpp"
#include "PlayerObject.cpp"
#include "Titleanim.cpp"
#include "BulletScript.cpp"
#include "Camera2D.cpp"
#include "PlayerScript.cpp"
#include "Titleanimscript.cpp"
#include "ToggleScript.cpp"
#include "AnimationClipManager.cpp"
#include "Collider.cpp"
#include "ColliderManager.cpp"
#include "ColliderPixel.cpp"
#include "Ray2D.cpp"
#include "Rigidbody.cpp"
// enemy list
#include "NormalEnemy.cpp"

#include "PlayerStartState.cpp"
#include "PlayerIdleState.cpp"
#include "PlayerDashState.cpp"
#include "PlayerJumpState.cpp"
#include "PlayerLandWallState.cpp"
#include "PlayerMoveState.cpp"
#include "PlayerShotState.cpp"
#include "FSMMarcine.cpp"
